### PR TITLE
getting ivan branch in line with main branch

### PR DESCRIPTION
**Pull request by Sonicbasedrop**

### CODE REVIEW

**Review by Sonicbasedrop — COMMENTED** [review]
getting ivan branch inline with main branch

**Review by Sonicbasedrop — COMMENTED** [review]
getting Ivan branch inline with main branch 2

**Review by Sonicbasedrop — COMMENTED** [review]
removed whitespace from idex page

**Review by Sonicbasedrop — COMMENTED** [review]
Adde content to README.mb

**Review by Sonicbasedrop — COMMENTED** [review]
added content  to the README.md

**Review by Sonicbasedrop — COMMENTED** [review]
Updated REDAME.md

**Review by Sonicbasedrop — COMMENTED** [review]
Visually looking true the previous changes

**Review by TashaTJ — APPROVED** [review]

**Pull request merged**
