### PR TITLE
Ivan

### PR DESCRIPTION
**Pull request by Sonicbasedrop**

### CODE REVIEW

**Comment by Sonicbasedrop** [comment]
404 page and styling is done :)

**Review by Sonicbasedrop — COMMENTED** [review]
LGTM

**Review by Sonicbasedrop — COMMENTED** [review]
Favicon uploaded

**Comment by Sonicbasedrop** [comment]
Favicon uploaded, witing for approval :)

**Review by mmcin — APPROVED** [review]
That is awesome!

**Pull request merged**
